//Options of <Form.Select /> in SearchForm component  

const options = [
    { key: 'a', text: '1', value: 1 },
    { key: 'b', text: '2', value: 2 },
    { key: 'c', text: '3', value: 3 },
    { key: 'd', text: '4', value: 4 },
    { key: 'e', text: '5', value: 5 },
    { key: 'f', text: '6', value: 6},
    { key: 'g', text: '7', value: 7 },
    { key: 'h', text: '8', value: 8 },
    { key: 'i', text: '9', value: 9 },
    { key: 'j', text: '10', value: 10 },
    { key: 'k', text: '11', value: 11 },
    { key: 'l', text: '12', value: 12 },
    { key: 'm', text: '13', value: 13},
    { key: 'n', text: '14', value: 14 },
    { key: 'o', text: '15', value: 15 },
    { key: 'p', text: '16', value: 16 },
    { key: 'q', text: '17', value: 17 },
    { key: 'r', text: '18', value: 18},
    { key: 's', text: '19', value: 19 },
    { key: 't', text: '20', value: 20 },
    { key: 'u', text: '21', value: 21 },
    { key: 'v', text: '22', value: 22},
    { key: 'w', text: '23', value: 23 },
    { key: 'x', text: '24', value: 24 },
    { key: 'y', text: '25', value: 25 },
    { key: 'z', text: '26', value: 26 },
    { key: 'ab', text: '27', value: 27 },
    { key: 'ac', text: '28', value: 28 },
    { key: 'ad', text: '29', value: 29 },
    { key: 'ae', text: '30', value: 30 },
  ]

  export default options;